openapi: 3.1.0
info:
  title: App Manifests
  description: Needs a description.
paths:
  /app-manifests/{code}/conversions:
    post:
      summary: Create a GitHub App from a manifest
      description: >-
        Use this endpoint to complete the handshake necessary when implementing
        the [GitHub App Manifest
        flow](https://docs.github.com/enterprise-server@3.9/apps/building-github-apps/creating-github-apps-from-a-manifest/).
        When you create a GitHub App with the manifest flow, you receive a
        temporary `code` used to retrieve the GitHub App's `id`, `pem` (private
        key), and `webhook_secret`.
      tags:
        - - - - apps
      operationId: apps/create-from-manifest
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/enterprise-server@3.9/rest/apps/apps#create-a-github-app-from-a-manifest
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
      responses:
        '201':
          description: Response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/integration'
                  - type: object
                    properties:
                      client_id:
                        type: string
                      client_secret:
                        type: string
                      webhook_secret:
                        type: string
                        nullable: true
                      pem:
                        type: string
                    required:
                      - client_id
                      - client_secret
                      - webhook_secret
                      - pem
                    additionalProperties: true
              examples:
                default:
                  $ref: '#/components/examples/integration-from-manifest'
        '404':
          $ref: '#/components/responses/not_found'
        '422':
          $ref: '#/components/responses/validation_failed_simple'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: apps
        subcategory: apps
components:
  schemas: {}
