openapi: 3.1.0
info:
  title: Feeds
  description: Needs a description.
paths:
  /feeds:
    get:
      summary: Get feeds
      description: >-
        GitHub Enterprise Server provides several timeline resources in
        [Atom](http://en.wikipedia.org/wiki/Atom_(standard)) format. The Feeds
        API lists all the feeds available to the authenticated user:


        *   **Timeline**: The GitHub Enterprise Server global public timeline

        *   **User**: The public timeline for any user, using `uri_template`.
        For more information, see
        "[Hypermedia](https://docs.github.com/enterprise-server@3.9/rest/using-the-rest-api/getting-started-with-the-rest-api#hypermedia)."

        *   **Current user public**: The public timeline for the authenticated
        user

        *   **Current user**: The private timeline for the authenticated user

        *   **Current user actor**: The private timeline for activity created by
        the authenticated user

        *   **Current user organizations**: The private timeline for the
        organizations the authenticated user is a member of.

        *   **Security advisories**: A collection of public announcements that
        provide information about security-related vulnerabilities in software
        on GitHub Enterprise Server.


        **Note**: Private feeds are only returned when [authenticating via Basic
        Auth](https://docs.github.com/enterprise-server@3.9/rest/overview/other-authentication-methods#basic-authentication)
        since current feed URIs use the older, non revocable auth tokens.
      tags:
        - - - - activity
      operationId: activity/get-feeds
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/enterprise-server@3.9/rest/activity/feeds#get-feeds
      parameters: []
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/feed'
              examples:
                default:
                  $ref: '#/components/examples/feed'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: activity
        subcategory: feeds
components:
  schemas:
    feed:
      title: Feed
      description: Feed
      type: object
      properties:
        timeline_url:
          type: string
          example: https://github.com/timeline
        user_url:
          type: string
          example: https://github.com/{user}
        current_user_public_url:
          type: string
          example: https://github.com/octocat
        current_user_url:
          type: string
          example: https://github.com/octocat.private?token=abc123
        current_user_actor_url:
          type: string
          example: https://github.com/octocat.private.actor?token=abc123
        current_user_organization_url:
          type: string
          example: https://github.com/octocat-org
        current_user_organization_urls:
          type: array
          example:
            - >-
              https://github.com/organizations/github/octocat.private.atom?token=abc123
          items:
            type: string
            format: uri
        security_advisories_url:
          type: string
          example: https://github.com/security-advisories
        repository_discussions_url:
          type: string
          example: https://github.com/{user}/{repo}/discussions
          description: A feed of discussions for a given repository.
        repository_discussions_category_url:
          type: string
          example: https://github.com/{user}/{repo}/discussions/categories/{category}
          description: A feed of discussions for a given repository and category.
        _links:
          type: object
          properties:
            timeline:
              $ref: '#/components/schemas/link-with-type'
            user:
              $ref: '#/components/schemas/link-with-type'
            security_advisories:
              $ref: '#/components/schemas/link-with-type'
            current_user:
              $ref: '#/components/schemas/link-with-type'
            current_user_public:
              $ref: '#/components/schemas/link-with-type'
            current_user_actor:
              $ref: '#/components/schemas/link-with-type'
            current_user_organization:
              $ref: '#/components/schemas/link-with-type'
            current_user_organizations:
              type: array
              items:
                $ref: '#/components/schemas/link-with-type'
            repository_discussions:
              $ref: '#/components/schemas/link-with-type'
            repository_discussions_category:
              $ref: '#/components/schemas/link-with-type'
          required:
            - timeline
            - user
      required:
        - _links
        - timeline_url
        - user_url
