openapi: 3.1.0
info:
  title: Manage
  description: Needs a description.
paths:
  /manage/v1/config/nodes:
    get:
      summary: Get GHES node metadata for all nodes
      description: >-
        Get node metadata for all configured nodes in the current cluster. For
        more information, see "[About
        clustering](https://docs.github.com/enterprise-server@3.9/admin/enterprise-management/configuring-clustering/about-clustering)."
      operationId: enterprise-admin/get-config-nodes
      tags:
        - - - - enterprise-admin
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/enterprise-server@3.9/rest/enterprise-admin/manage-ghes#get-ghes-node-metadata-for-all-nodes
      servers:
        - url: '{protocol}://{hostname}'
          variables:
            hostname:
              default: HOSTNAME
              description: Self-hosted Enterprise Server hostname
            protocol:
              default: http
              description: Self-hosted Enterprise Server protocol
      parameters:
        - $ref: '#/components/parameters/uuid'
        - $ref: '#/components/parameters/cluster-roles'
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ghes-config-nodes'
              examples:
                default:
                  $ref: '#/components/examples/ghes-config-nodes'
        '401':
          description: Unauthorized
        '500':
          description: Internal error
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: enterprise-admin
        subcategory: manage-ghes
  /manage/v1/replication/status:
    get:
      summary: Get the status of services running on all replica nodes
      description: |-
        Gets the status of all services running on each replica node.
        This endpoint may take several seconds to reply.
      operationId: enterprise-admin/get-replication-status
      tags:
        - - - - enterprise-admin
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/enterprise-server@3.9/rest/enterprise-admin/manage-ghes#get-the-status-of-services-running-on-all-replica-nodes
      servers:
        - url: '{protocol}://{hostname}'
          variables:
            hostname:
              default: HOSTNAME
              description: Self-hosted Enterprise Server hostname
            protocol:
              default: http
              description: Self-hosted Enterprise Server protocol
      parameters:
        - $ref: '#/components/parameters/uuid'
        - $ref: '#/components/parameters/cluster-roles'
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ghes-replication-status'
              examples:
                default:
                  $ref: '#/components/examples/ghes-replication-status'
        '401':
          description: Unauthorized
        '500':
          description: Internal error
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: enterprise-admin
        subcategory: manage-ghes
  /manage/v1/version:
    get:
      summary: Get all GHES release versions for all nodes
      description: >-
        Gets the GitHub Enterprise Server release versions that are currently
        installed on all available nodes. For more information, see "[GitHub
        Enterprise Server
        releases](https://docs.github.com/enterprise-server@3.9/admin/all-releases)."
      operationId: enterprise-admin/get-version
      tags:
        - - - - enterprise-admin
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/enterprise-server@3.9/rest/enterprise-admin/manage-ghes#get-all-ghes-release-versions-for-all-nodes
      servers:
        - url: '{protocol}://{hostname}'
          variables:
            hostname:
              default: HOSTNAME
              description: Self-hosted Enterprise Server hostname
            protocol:
              default: http
              description: Self-hosted Enterprise Server protocol
      parameters:
        - $ref: '#/components/parameters/uuid'
        - $ref: '#/components/parameters/cluster-roles'
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ghes-version'
              examples:
                default:
                  $ref: '#/components/examples/ghes-version'
        '401':
          description: Unauthorized
        '500':
          description: Internal error
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: enterprise-admin
        subcategory: manage-ghes
components:
  schemas:
    ghes-config-nodes:
      type: object
      properties:
        topology:
          $ref: '#/components/schemas/ghes-cluster-topology'
        nodes:
          type: array
          items:
            type: object
            properties:
              hostname:
                type: string
              uuid:
                type: string
              replica:
                type: boolean
              cluster_roles:
                type: array
                items:
                  $ref: '#/components/schemas/ghes-cluster-roles'
    ghes-replication-status:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/ghes-replication-status-indicator'
        nodes:
          type: array
          items:
            type: object
            properties:
              hostname:
                type: string
              status:
                $ref: '#/components/schemas/ghes-replication-status-indicator'
              services:
                type: array
                items:
                  type: object
                  properties:
                    status:
                      $ref: '#/components/schemas/ghes-replication-status-indicator'
                    name:
                      type: string
                    details:
                      type: string
    ghes-version:
      type: array
      items:
        type: object
        properties:
          hostname:
            type: string
            format: hostname
          version:
            type: object
            properties:
              version:
                type: string
                pattern: '[0-9]\.[0-9]{2}\.[0-9]'
              platform:
                type: string
                enum:
                  - ami
                  - azure
                  - esx
                  - gce
                  - hyperv
                  - kvm
              build_id:
                type: string
                pattern: '[0-9a-f]{8}'
              build_date:
                type: string
                format: date
