openapi: 3.1.0
info:
  title: Notifications
  description: Needs a description.
paths:
  /notifications:
    get:
      summary: List notifications for the authenticated user
      description: >-
        List all notifications for the current user, sorted by most recently
        updated.
      tags:
        - - - - activity
      operationId: activity/list-notifications-for-authenticated-user
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/enterprise-server@3.9/rest/activity/notifications#list-notifications-for-the-authenticated-user
      parameters:
        - $ref: '#/components/parameters/all'
        - $ref: '#/components/parameters/participating'
        - $ref: '#/components/parameters/since'
        - $ref: '#/components/parameters/before'
        - $ref: '#/components/parameters/page'
        - name: per_page
          description: >-
            The number of results per page (max 50). For more information, see
            "[Using pagination in the REST
            API](https://docs.github.com/enterprise-server@3.9/rest/using-the-rest-api/using-pagination-in-the-rest-api)."
          in: query
          schema:
            type: integer
            default: 50
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/thread'
              examples:
                default:
                  $ref: '#/components/examples/thread-items'
          headers:
            Link:
              $ref: '#/components/headers/link'
        '304':
          $ref: '#/components/responses/not_modified'
        '401':
          $ref: '#/components/responses/requires_authentication'
        '403':
          $ref: '#/components/responses/forbidden'
        '422':
          $ref: '#/components/responses/validation_failed'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: activity
        subcategory: notifications
    put:
      summary: Mark notifications as read
      description: >-
        Marks all notifications as "read" for the current user. If the number of
        notifications is too large to complete in one request, you will receive
        a `202 Accepted` status and GitHub Enterprise Server will run an
        asynchronous process to mark notifications as "read." To check whether
        any "unread" notifications remain, you can use the [List notifications
        for the authenticated
        user](https://docs.github.com/enterprise-server@3.9/rest/activity/notifications#list-notifications-for-the-authenticated-user)
        endpoint and pass the query parameter `all=false`.
      tags:
        - - - - activity
      operationId: activity/mark-notifications-as-read
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/enterprise-server@3.9/rest/activity/notifications#mark-notifications-as-read
      parameters: []
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                last_read_at:
                  description: >-
                    Describes the last point that notifications were checked.
                    Anything updated since this time will not be marked as read.
                    If you omit this parameter, all notifications are marked as
                    read. This is a timestamp in [ISO
                    8601](https://en.wikipedia.org/wiki/ISO_8601) format:
                    `YYYY-MM-DDTHH:MM:SSZ`. Default: The current timestamp.
                  type: string
                  format: date-time
                read:
                  description: Whether the notification has been read.
                  type: boolean
            examples:
              default:
                value:
                  last_read_at: '2022-06-10T00:00:00Z'
                  read: true
      responses:
        '202':
          description: Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              examples:
                default:
                  $ref: '#/components/examples/notifications-mark-read'
        '205':
          description: Reset Content
        '304':
          $ref: '#/components/responses/not_modified'
        '401':
          $ref: '#/components/responses/requires_authentication'
        '403':
          $ref: '#/components/responses/forbidden'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: activity
        subcategory: notifications
  /notifications/threads/{thread_id}:
    get:
      summary: Get a thread
      description: Gets information about a notification thread.
      tags:
        - - - - activity
      operationId: activity/get-thread
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/enterprise-server@3.9/rest/activity/notifications#get-a-thread
      parameters:
        - $ref: '#/components/parameters/thread-id'
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/thread'
              examples:
                default:
                  $ref: '#/components/examples/thread'
        '304':
          $ref: '#/components/responses/not_modified'
        '401':
          $ref: '#/components/responses/requires_authentication'
        '403':
          $ref: '#/components/responses/forbidden'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: activity
        subcategory: notifications
    patch:
      summary: Mark a thread as read
      description: >-
        Marks a thread as "read." Marking a thread as "read" is equivalent to
        clicking a notification in your notification inbox on GitHub Enterprise
        Server: https://github.com/notifications.
      tags:
        - - - - activity
      operationId: activity/mark-thread-as-read
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/enterprise-server@3.9/rest/activity/notifications#mark-a-thread-as-read
      parameters:
        - $ref: '#/components/parameters/thread-id'
      responses:
        '205':
          description: Reset Content
        '304':
          $ref: '#/components/responses/not_modified'
        '403':
          $ref: '#/components/responses/forbidden'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: activity
        subcategory: notifications
  /notifications/threads/{thread_id}/subscription:
    get:
      summary: Get a thread subscription for the authenticated user
      description: >-
        This checks to see if the current user is subscribed to a thread. You
        can also [get a repository
        subscription](https://docs.github.com/enterprise-server@3.9/rest/activity/watching#get-a-repository-subscription).


        Note that subscriptions are only generated if a user is participating in
        a conversation--for example, they've replied to the thread, were
        **@mentioned**, or manually subscribe to a thread.
      tags:
        - - - - activity
      operationId: activity/get-thread-subscription-for-authenticated-user
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/enterprise-server@3.9/rest/activity/notifications#get-a-thread-subscription-for-the-authenticated-user
      parameters:
        - $ref: '#/components/parameters/thread-id'
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/thread-subscription'
              examples:
                default:
                  $ref: '#/components/examples/thread-subscription'
        '304':
          $ref: '#/components/responses/not_modified'
        '401':
          $ref: '#/components/responses/requires_authentication'
        '403':
          $ref: '#/components/responses/forbidden'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: activity
        subcategory: notifications
    put:
      summary: Set a thread subscription
      description: >-
        If you are watching a repository, you receive notifications for all
        threads by default. Use this endpoint to ignore future notifications for
        threads until you comment on the thread or get an **@mention**.


        You can also use this endpoint to subscribe to threads that you are
        currently not receiving notifications for or to subscribed to threads
        that you have previously ignored.


        Unsubscribing from a conversation in a repository that you are not
        watching is functionally equivalent to the [Delete a thread
        subscription](https://docs.github.com/enterprise-server@3.9/rest/activity/notifications#delete-a-thread-subscription)
        endpoint.
      tags:
        - - - - activity
      operationId: activity/set-thread-subscription
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/enterprise-server@3.9/rest/activity/notifications#set-a-thread-subscription
      parameters:
        - $ref: '#/components/parameters/thread-id'
      requestBody:
        required: false
        content:
          application/json:
            schema:
              properties:
                ignored:
                  description: Whether to block all notifications from a thread.
                  default: false
                  type: boolean
              type: object
            examples:
              default:
                value:
                  ignored: false
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/thread-subscription'
              examples:
                default:
                  $ref: '#/components/examples/thread-subscription'
        '304':
          $ref: '#/components/responses/not_modified'
        '401':
          $ref: '#/components/responses/requires_authentication'
        '403':
          $ref: '#/components/responses/forbidden'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: activity
        subcategory: notifications
    delete:
      summary: Delete a thread subscription
      description: >-
        Mutes all future notifications for a conversation until you comment on
        the thread or get an **@mention**. If you are watching the repository of
        the thread, you will still receive notifications. To ignore future
        notifications for a repository you are watching, use the [Set a thread
        subscription](https://docs.github.com/enterprise-server@3.9/rest/activity/notifications#set-a-thread-subscription)
        endpoint and set `ignore` to `true`.
      tags:
        - - - - activity
      operationId: activity/delete-thread-subscription
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/enterprise-server@3.9/rest/activity/notifications#delete-a-thread-subscription
      parameters:
        - $ref: '#/components/parameters/thread-id'
      responses:
        '204':
          description: Response
        '304':
          $ref: '#/components/responses/not_modified'
        '401':
          $ref: '#/components/responses/requires_authentication'
        '403':
          $ref: '#/components/responses/forbidden'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: activity
        subcategory: notifications
  /repos/{owner}/{repo}/notifications:
    get:
      summary: List repository notifications for the authenticated user
      description: >-
        Lists all notifications for the current user in the specified
        repository.
      tags:
        - - - - activity
      operationId: activity/list-repo-notifications-for-authenticated-user
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/enterprise-server@3.9/rest/activity/notifications#list-repository-notifications-for-the-authenticated-user
      parameters:
        - $ref: '#/components/parameters/owner'
        - $ref: '#/components/parameters/repo'
        - $ref: '#/components/parameters/all'
        - $ref: '#/components/parameters/participating'
        - $ref: '#/components/parameters/since'
        - $ref: '#/components/parameters/before'
        - $ref: '#/components/parameters/per-page'
        - $ref: '#/components/parameters/page'
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/thread'
              examples:
                default:
                  $ref: '#/components/examples/thread-items'
          headers:
            Link:
              $ref: '#/components/headers/link'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: activity
        subcategory: notifications
    put:
      summary: Mark repository notifications as read
      description: >-
        Marks all notifications in a repository as "read" for the current user.
        If the number of notifications is too large to complete in one request,
        you will receive a `202 Accepted` status and GitHub Enterprise Server
        will run an asynchronous process to mark notifications as "read." To
        check whether any "unread" notifications remain, you can use the [List
        repository notifications for the authenticated
        user](https://docs.github.com/enterprise-server@3.9/rest/activity/notifications#list-repository-notifications-for-the-authenticated-user)
        endpoint and pass the query parameter `all=false`.
      tags:
        - - - - activity
      operationId: activity/mark-repo-notifications-as-read
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/enterprise-server@3.9/rest/activity/notifications#mark-repository-notifications-as-read
      parameters:
        - $ref: '#/components/parameters/owner'
        - $ref: '#/components/parameters/repo'
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                last_read_at:
                  type: string
                  format: date-time
                  description: >-
                    Describes the last point that notifications were checked.
                    Anything updated since this time will not be marked as read.
                    If you omit this parameter, all notifications are marked as
                    read. This is a timestamp in [ISO
                    8601](https://en.wikipedia.org/wiki/ISO_8601) format:
                    `YYYY-MM-DDTHH:MM:SSZ`. Default: The current timestamp.
            examples:
              default:
                value:
                  last_read_at: '2019-01-01T00:00:00Z'
      responses:
        '202':
          description: Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  url:
                    type: string
              examples:
                default:
                  value:
                    message: >-
                      Unread notifications couldn't be marked in a single
                      request. Notifications are being marked as read in the
                      background.
        '205':
          description: Reset Content
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: activity
        subcategory: notifications
components:
  schemas:
    thread:
      title: Thread
      description: Thread
      type: object
      properties:
        id:
          type: string
        repository:
          $ref: '#/components/schemas/minimal-repository'
        subject:
          type: object
          properties:
            title:
              type: string
            url:
              type: string
            latest_comment_url:
              type: string
            type:
              type: string
          required:
            - title
            - url
            - latest_comment_url
            - type
        reason:
          type: string
        unread:
          type: boolean
        updated_at:
          type: string
        last_read_at:
          type: string
          nullable: true
        url:
          type: string
        subscription_url:
          type: string
          example: https://api.github.com/notifications/threads/2/subscription
      required:
        - id
        - unread
        - reason
        - updated_at
        - last_read_at
        - subject
        - repository
        - url
        - subscription_url
    thread-subscription:
      title: Thread Subscription
      description: Thread Subscription
      type: object
      properties:
        subscribed:
          type: boolean
          example: true
        ignored:
          type: boolean
        reason:
          type: string
          nullable: true
        created_at:
          type: string
          format: date-time
          example: '2012-10-06T21:34:12Z'
          nullable: true
        url:
          type: string
          format: uri
          example: https://api.github.com/notifications/threads/1/subscription
        thread_url:
          type: string
          format: uri
          example: https://api.github.com/notifications/threads/1
        repository_url:
          type: string
          format: uri
          example: https://api.github.com/repos/1
      required:
        - created_at
        - ignored
        - reason
        - url
        - subscribed
