openapi: 3.1.0
info:
  title: Octocat
  description: Needs a description.
paths:
  /octocat:
    get:
      summary: Get Octocat
      description: Get the octocat as ASCII art
      tags:
        - - - - meta
      operationId: meta/get-octocat
      parameters:
        - name: s
          in: query
          description: The words to show in Octocat's speech bubble
          schema:
            type: string
          required: false
      responses:
        '200':
          description: Response
          content:
            application/octocat-stream:
              schema:
                type: string
              examples:
                default:
                  $ref: '#/components/examples/octocat'
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/enterprise-server@3.9/rest/meta/meta#get-octocat
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: meta
        subcategory: meta
components:
  schemas: {}
