openapi: 3.1.0
info:
  title: Zen
  description: Needs a description.
paths:
  /zen:
    get:
      summary: Get the Zen of GitHub
      description: Get a random sentence from the Zen of GitHub
      tags:
        - - - - meta
      operationId: meta/get-zen
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/enterprise-server@3.9/rest/meta/meta#get-the-zen-of-github
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                type: string
              examples:
                default:
                  summary: Example response
                  value: Responsive is better than fast
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: meta
        subcategory: meta
components:
  schemas: {}
